### ISSUE TITLE
When utilizing BM25, i see this version token error

### ISSUE THREAD

**Issue by vaibhavsav** [Teddy-XiongGZ/MedRAG#21]
Hello! I am trying to run RRF-4 retriever. When embedding data with BM25, i see this error with chunk/pubmed. I am utilizing java 11 for running this as it requires java. 

Is there any specific java version you are running? 

```
2024-10-24 15:09:17,967 INFO  [main] index.IndexCollection (IndexCollection.java:512) - Initializing collection in ./corpus/pubmed/chunk
2024-10-24 15:09:17,988 INFO  [main] index.IndexCollection (IndexCollection.java:521) - 1,166 files found
2024-10-24 15:09:17,988 INFO  [main] index.IndexCollection (IndexCollection.java:522) - Starting to index...
2024-10-24 15:09:18,029 ERROR [pool-2-thread-5] index.IndexCollection$LocalIndexerThread (IndexCollection.java:348) - pool-2-thread-5: Unexpected Exception:
2024-10-24 15:09:18,029 ERROR [pool-2-thread-5] index.IndexCollection$LocalIndexerThread (IndexCollection.java:348) - pool-2-thread-5: Unexpected Exception:
com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'version': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
 at [Source: (BufferedReader); line: 1, column: 8]
        at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:2418) ~[anserini-0.22.1-fatjar.jar:?]
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:759) ~[anserini-0.22.1-fatjar.jar:?]
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._reportInvalidToken(ReaderBasedJsonParser.java:3038) ~[anserini-0.22.1-fatjar.jar:?]
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:2079) ~[anserini-0.22.1-fatjar.jar:?]
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:805) ~[anserini-0.22.1-fatjar.jar:?]
        at com.fasterxml.jackson.databind.ObjectReader.readValues(ObjectReader.java:1929) ~[anserini-0.22.1-fatjar.jar:?]
        at io.anserini.collection.JsonCollection$Segment.<init>(JsonCollection.java:117) ~[anserini-0.22.1-fatjar.jar:?]
        at io.anserini.collection.JsonCollection.createFileSegment(JsonCollection.java:90) ~[anserini-0.22.1-fatjar.jar:?]
        at io.anserini.index.IndexCollection$LocalIndexerThread.run(IndexCollection.java:283) [anserini-0.22.1-fatjar.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:829) [?:?]
```

**Comment by gzxiong** [comment]
Sorry for the late reply. I'm using Java/21.

**Comment by manglu097** [comment]
How many GB of video memory are needed when using BM25?

**Comment by gzxiong** [comment]
Hi @manglu097, BM25 in our project is primarily executed on CPUs. As an approximate reference, the BM25 index files for PubMed occupy about 4 GB of disk space.
