### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by happyrenxiaozhao** [Teddy-XiongGZ/MedRAG#22]
Hi, my questions are as follows, please help me:

Traceback (most recent call last):
  File "/home/ubuntu/pycharm-community-2023.1.3/plugins/python-ce/helpers/pydev/pydevd.py", line 1500, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/ubuntu/pycharm-community-2023.1.3/plugins/python-ce/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/ubuntu/Renxiaozhao/MedRAG/eval_test_llama3.py", line 22, in <module>
    answer, snippets, scores = medrag.answer(question=question, options=options,
  File "/home/ubuntu/Renxiaozhao/MedRAG/src/medrag.py", line 207, in medrag_answer
    retrieved_snippets, scores = self.retrieval_system.retrieve(question, k=k, rrf_k=rrf_k)
  File "/home/ubuntu/Renxiaozhao/MedRAG/src/utils.py", line 274, in retrieve
    t, s = self.retrievers[i][j].get_relevant_documents(question, k=k_, id_only=id_only)
  File "/home/ubuntu/Renxiaozhao/MedRAG/src/utils.py", line 226, in get_relevant_documents
    return self.idx2txt(indices), scores
  File "/home/ubuntu/Renxiaozhao/MedRAG/src/utils.py", line 233, in idx2txt
    return [json.loads(open(os.path.join(self.chunk_dir, i["source"]+".jsonl")).read().strip().split('\n')[i["index"]]) for i in indices]
  File "/home/ubuntu/Renxiaozhao/MedRAG/src/utils.py", line 233, in <listcomp>
    return [json.loads(open(os.path.join(self.chunk_dir, i["source"]+".jsonl")).read().strip().split('\n')[i["index"]]) for i in indices]
IndexError: list index out of range

**Comment by gzxiong** [comment]
Hi, could you please first check if the chunks are properly downloaded from huggingface? The issue may occur if you didn't load `git-lfs` and failed to download the chunks.
